CREATE DATABASE IF NOT EXISTS NUTRIENT;

USE NUTRIENT;

DROP TABLE IF EXISTS SOR;
DROP TABLE IF EXISTS SORR;
DROP TABLE IF EXISTS HEALTHFOODFUNC;

CREATE TABLE IF NOT EXISTS SOR (
	PRDLST_REPORT_NO VARCHAR(50),
	PRMS_DT VARCHAR(50),
	PRDT_SHAP_CD_NM VARCHAR(50),
	LAST_UPDT_DTM VARCHAR(100),
	LCNS_NO VARCHAR(50),
	PRDLST_NM VARCHAR(200),
	IFTKN_ATNT_MATR_CN TEXT,
	BSSH_NM VARCHAR(500),
	CHILD_CRTFC_YN VARCHAR(500),
	ETC_RAWMTRL_NM TEXT,
	STDR_STND TEXT,
	PRDLST_CDNM VARCHAR(500),
	INDUTY_CD_NM VARCHAR(500),
	DISPOS VARCHAR(500),
	PRIMARY_FNCLTY TEXT,
	FRMLC_MTRQLT TEXT,
	POG_DAYCNT VARCHAR(200),
	CSTDY_MTHD VARCHAR(500),
	INDIV_RAWMTRL_NM TEXT,
	NTK_MTHD VARCHAR(500),
	HIENG_LNTRT_DVS_NM VARCHAR(200),
	RAWMTRL_NM TEXT,
	PRODUCTION VARCHAR(200),
	CAP_RAWMTRL_NM TEXT
) CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE TABLE IF NOT EXISTS SORR (
	LCNS_NO	VARCHAR(50),
	BSSH_NM	VARCHAR(50),
	PRDLST_REPORT_NO VARCHAR(50),
	PRDLST_NM VARCHAR(500),
	PRMS_DT VARCHAR(500),
	POG_DAYCNT VARCHAR(500),
	DISPOS VARCHAR(500),
	NTK_MTHD VARCHAR(500),
	PRIMARY_FNCLTY TEXT,
	IFTKN_ATNT_MATR_CN TEXT,
	CSTDY_MTHD VARCHAR(500),
	SHAP VARCHAR(500),
	STDR_STND TEXT,
	RAWMTRL_NM TEXT,
	CRET_DTM VARCHAR(500),
	LAST_UPDT_DTM VARCHAR(500),
	PRDT_SHAP_CD_NM VARCHAR(500)
) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

# 건강기능식품공전
CREATE TABLE IF NOT EXISTS HEALTHFOODFUNC (
	PRDLST_CD VARCHAR(20) NOT NULL, # 품목코드
    PC_KOR_NM VARCHAR(200) NOT NULL, # 품목한글명
    TESTITM_CD VARCHAR(20) NOT NULL, # 시험항목코드
    T_KOR_NM VARCHAR(200),	# 시험항목 한글명
    FNPRT_ITM_NM VARCHAR(20),	# 세부항목명
    SPEC_VAL VARCHAR(20),	# 기준규격 값
    SPEC_VAL_SUMUP VARCHAR(500),	# 기준규격값 요약
    VALD_BEGN_DT VARCHAR(20),	# 유효개시일자
    VALD_END_DT VARCHAR(20),	# 유효종료일자
    SORC VARCHAR(200),	# 출처
    MXMM_VAL VARCHAR(20),	# 최대값
    NIMM_VAL VARCHAR(20),	# 최소값
    INJRY_YN VARCHAR(20),	# 위해여부
    UNIT_NM VARCHAR(20)	# 단위명
    # PRIMARY KEY(PRDLST_CD, PC_KOR_NM, TESTITM_CD, T_KOR_NM, SPEC_VAL, SPEC_VAL_SUMUP)
) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SHOW TABLES;
desc HEALTHFOODFUNC;

select * from healthFoodFunc;
select * from HEALTHFOODFUNC where not replace(pc_kor_nm, ' ', '') like concat('%', replace(t_kor_nm, ' ', ''), '%');
select * 
from HEALTHFOODFUNC 
where (
	select count(t_kor_nm)
    from HEALTHFOODFUNC
) > 100;
select * from HEALTHFOODFUNC where PC_KOR_NM like '%프로바이오틱스%';

alter table HEALTHFOODFUNC modify SORC VARCHAR(200);

alter table sor convert to character set utf8 collate utf8_general_ci;

select count(*) from HEALTHFOODFUNC;

select prdlst_report_no, stdr_stnd from sor where not STDR_STND like "%:%";
select stdr_stnd from sor where STDR_STND like "%비타민 C%";
select * from sor where PRDLST_NM like "%밀크씨슬 헬퍼%";
select count(*) from sorr;
select * from sorr where STDR_STND like "%0.45mg%";

desc sor;