CREATE DATABASE IF NOT EXISTS NUTRIENT;

USE NUTRIENT;

DROP TABLE IF EXISTS SOR;
DROP TABLE IF EXISTS SORR;

CREATE TABLE IF NOT EXISTS SOR (
	PRDLST_REPORT_NO VARCHAR(50),
	PRMS_DT VARCHAR(50),
	PRDT_SHAP_CD_NM VARCHAR(50),
	LAST_UPDT_DTM VARCHAR(100),
	LCNS_NO VARCHAR(50),
	PRDLST_NM VARCHAR(200),
	IFTKN_ATNT_MATR_CN TEXT,
	BSSH_NM VARCHAR(500),
	CHILD_CRTFC_YN VARCHAR(500),
	ETC_RAWMTRL_NM TEXT,
	STDR_STND TEXT,
	PRDLST_CDNM VARCHAR(500),
	INDUTY_CD_NM VARCHAR(500),
	DISPOS VARCHAR(500),
	PRIMARY_FNCLTY TEXT,
	FRMLC_MTRQLT TEXT,
	POG_DAYCNT VARCHAR(200),
	CSTDY_MTHD VARCHAR(500),
	INDIV_RAWMTRL_NM TEXT,
	NTK_MTHD VARCHAR(500),
	HIENG_LNTRT_DVS_NM VARCHAR(200),
	RAWMTRL_NM TEXT,
	PRODUCTION VARCHAR(200),
	CAP_RAWMTRL_NM VARCHAR(500)
) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

CREATE TABLE IF NOT EXISTS SORR (
	LCNS_NO	VARCHAR(50),
	BSSH_NM	VARCHAR(50),
	PRDLST_REPORT_NO VARCHAR(50),
	PRDLST_NM VARCHAR(500),
	PRMS_DT VARCHAR(500),
	POG_DAYCNT VARCHAR(500),
	DISPOS VARCHAR(500),
	NTK_MTHD VARCHAR(500),
	PRIMARY_FNCLTY TEXT,
	IFTKN_ATNT_MATR_CN TEXT,
	CSTDY_MTHD VARCHAR(500),
	SHAP VARCHAR(500),
	STDR_STND TEXT,
	RAWMTRL_NM TEXT,
	CRET_DTM VARCHAR(500),
	LAST_UPDT_DTM VARCHAR(500),
	PRDT_SHAP_CD_NM VARCHAR(500)
) CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

SHOW TABLES;

alter table sor modify PRDLST_NM varchar(200);

select count(*) from sor;
select count(*) from sorr;

desc sor;